[package]
name = "lili-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
hydrate = ["dep:wasm-bindgen", "leptos/hydrate"]
ssr = ["leptos/ssr"]

[dependencies]
leptos.workspace = true
wasm-bindgen = { workspace = true, optional = true }
