[package]
name = "lili-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
hydrate = [
  "dep:js-sys",
  "dep:wasm-bindgen",
  "dep:wasm-bindgen-futures",
  "dep:web-sys",
  "leptos/hydrate",
]
ssr = ["leptos/ssr"]

[dependencies]
leptos.workspace = true
js-sys = { workspace = true, optional = true }
lili-core = { path = "../lili-core" }
lili-pet = { path = "../lili-pet" }
serde_json.workspace = true
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
web-sys = { workspace = true, features = [
  "AnimationEvent",
  "CssStyleDeclaration",
  "Document",
  "DomRect",
  "Element",
  "EventSource",
  "HtmlElement",
  "MessageEvent",
  "MediaQueryList",
  "KeyboardEvent",
  "PointerEvent",
  "Performance",
  "TransitionEvent",
  "WheelEvent",
  "Window",
], optional = true }
