[package]
name = "lili-web"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
lili-app-state = { path = "../lili-app-state" }
lili-server = { path = "../lili-server" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
