[package]
name = "lili"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "lili_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
serde_json.workspace = true
tauri-build.workspace = true

[dependencies]
tauri = { workspace = true, features = ["macos-private-api"] }
