name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish-release:
    uses: ./.github/workflows/Publish-Release.yaml
    with:
      artifact-prefix: lili-release
      publish: ${{ github.ref_type == 'tag' }}
